version: '3'
services:
  node:
    image: "nanocurrency/nano:${NANO_TAG}"
    restart: "unless-stopped"
    ports:
    - "7075:7075/udp" #udp network traffic (deprecated since V21)
    - "7075:7075" #tcp network traffic
    - "127.0.0.1:7076:7076" #rpc to localhost only
    - "127.0.0.1:7078:7078" #websocket to localhost only
    volumes:
    - "${NANO_HOST_DIR}:/root"

  rabbitmq:
    image: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15671:15671
      - 15672:15672
      - 25672:25672
      - 5671:5671
      - 5672:5672
      - 4369:4369