version: '3'
services:
  node:
    image: "nanocurrency/nano:${NANO_TAG}"
    restart: "unless-stopped"
    ports:
    - "7075:7075/udp" #udp network traffic (deprecated since V21)
    - "7075:7075" #tcp network traffic
    - "127.0.0.1:7076:7076" #rpc to localhost only
    - "127.0.0.1:7078:7078" #websocket to localhost only
    volumes:
    - "${NANO_HOST_DIR}:/root"