// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: webhook_job.proto

package spec

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WebhookJobAction int32

const (
	WebhookJobAction_CREATE WebhookJobAction = 0
	WebhookJobAction_UPDATE WebhookJobAction = 1
	WebhookJobAction_DELETE WebhookJobAction = 2
)

// Enum value maps for WebhookJobAction.
var (
	WebhookJobAction_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	WebhookJobAction_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x WebhookJobAction) Enum() *WebhookJobAction {
	p := new(WebhookJobAction)
	*p = x
	return p
}

func (x WebhookJobAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookJobAction) Descriptor() protoreflect.EnumDescriptor {
	return file_webhook_job_proto_enumTypes[0].Descriptor()
}

func (WebhookJobAction) Type() protoreflect.EnumType {
	return &file_webhook_job_proto_enumTypes[0]
}

func (x WebhookJobAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookJobAction.Descriptor instead.
func (WebhookJobAction) EnumDescriptor() ([]byte, []int) {
	return file_webhook_job_proto_rawDescGZIP(), []int{0}
}

type ActionResult int32

const (
	ActionResult_SUCCESSFUL ActionResult = 0
	ActionResult_ERROR      ActionResult = 1
)

// Enum value maps for ActionResult.
var (
	ActionResult_name = map[int32]string{
		0: "SUCCESSFUL",
		1: "ERROR",
	}
	ActionResult_value = map[string]int32{
		"SUCCESSFUL": 0,
		"ERROR":      1,
	}
)

func (x ActionResult) Enum() *ActionResult {
	p := new(ActionResult)
	*p = x
	return p
}

func (x ActionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_webhook_job_proto_enumTypes[1].Descriptor()
}

func (ActionResult) Type() protoreflect.EnumType {
	return &file_webhook_job_proto_enumTypes[1]
}

func (x ActionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionResult.Descriptor instead.
func (ActionResult) EnumDescriptor() ([]byte, []int) {
	return file_webhook_job_proto_rawDescGZIP(), []int{1}
}

type WebhookJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Accounts  []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Recipient string   `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *WebhookJob) Reset() {
	*x = WebhookJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookJob) ProtoMessage() {}

func (x *WebhookJob) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookJob.ProtoReflect.Descriptor instead.
func (*WebhookJob) Descriptor() ([]byte, []int) {
	return file_webhook_job_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookJob) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *WebhookJob) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type WebhookJobMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action     WebhookJobAction `protobuf:"varint,2,opt,name=action,proto3,enum=main.WebhookJobAction" json:"action,omitempty"`
	WebhookJob *WebhookJob      `protobuf:"bytes,3,opt,name=webhookJob,proto3" json:"webhookJob,omitempty"`
	ReplyTo    string           `protobuf:"bytes,4,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
}

func (x *WebhookJobMessage) Reset() {
	*x = WebhookJobMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookJobMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookJobMessage) ProtoMessage() {}

func (x *WebhookJobMessage) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookJobMessage.ProtoReflect.Descriptor instead.
func (*WebhookJobMessage) Descriptor() ([]byte, []int) {
	return file_webhook_job_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookJobMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WebhookJobMessage) GetAction() WebhookJobAction {
	if x != nil {
		return x.Action
	}
	return WebhookJobAction_CREATE
}

func (x *WebhookJobMessage) GetWebhookJob() *WebhookJob {
	if x != nil {
		return x.WebhookJob
	}
	return nil
}

func (x *WebhookJobMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

type WebhookJobReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status    ActionResult `protobuf:"varint,2,opt,name=status,proto3,enum=main.ActionResult" json:"status,omitempty"`
	ErrorInfo string       `protobuf:"bytes,3,opt,name=errorInfo,proto3" json:"errorInfo,omitempty"`
}

func (x *WebhookJobReply) Reset() {
	*x = WebhookJobReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookJobReply) ProtoMessage() {}

func (x *WebhookJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookJobReply.ProtoReflect.Descriptor instead.
func (*WebhookJobReply) Descriptor() ([]byte, []int) {
	return file_webhook_job_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookJobReply) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WebhookJobReply) GetStatus() ActionResult {
	if x != nil {
		return x.Status
	}
	return ActionResult_SUCCESSFUL
}

func (x *WebhookJobReply) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

var File_webhook_job_proto protoreflect.FileDescriptor

var file_webhook_job_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x56, 0x0a, 0x0a, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x0a, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62, 0x52,
	0x0a, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4a, 0x6f, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x54, 0x6f, 0x22, 0x6d, 0x0a, 0x0f, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x36, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4a,
	0x6f, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x29, 0x0a, 0x0c,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x46, 0x55, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x73, 0x70, 0x65,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_webhook_job_proto_rawDescOnce sync.Once
	file_webhook_job_proto_rawDescData = file_webhook_job_proto_rawDesc
)

func file_webhook_job_proto_rawDescGZIP() []byte {
	file_webhook_job_proto_rawDescOnce.Do(func() {
		file_webhook_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_webhook_job_proto_rawDescData)
	})
	return file_webhook_job_proto_rawDescData
}

var file_webhook_job_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_webhook_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webhook_job_proto_goTypes = []interface{}{
	(WebhookJobAction)(0),     // 0: main.WebhookJobAction
	(ActionResult)(0),         // 1: main.ActionResult
	(*WebhookJob)(nil),        // 2: main.WebhookJob
	(*WebhookJobMessage)(nil), // 3: main.WebhookJobMessage
	(*WebhookJobReply)(nil),   // 4: main.WebhookJobReply
}
var file_webhook_job_proto_depIdxs = []int32{
	0, // 0: main.WebhookJobMessage.action:type_name -> main.WebhookJobAction
	2, // 1: main.WebhookJobMessage.webhookJob:type_name -> main.WebhookJob
	1, // 2: main.WebhookJobReply.status:type_name -> main.ActionResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_webhook_job_proto_init() }
func file_webhook_job_proto_init() {
	if File_webhook_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webhook_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webhook_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookJobMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webhook_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookJobReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webhook_job_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webhook_job_proto_goTypes,
		DependencyIndexes: file_webhook_job_proto_depIdxs,
		EnumInfos:         file_webhook_job_proto_enumTypes,
		MessageInfos:      file_webhook_job_proto_msgTypes,
	}.Build()
	File_webhook_job_proto = out.File
	file_webhook_job_proto_rawDesc = nil
	file_webhook_job_proto_goTypes = nil
	file_webhook_job_proto_depIdxs = nil
}
